name: Liquibase PoC via Cloud Run Job

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ "liquibase/**", "bin/**", "cloudrun/**" ]

permissions:
  contents: read

env:
  GCP_PROJECT: autodeploydb
  GCP_REGION: us-central1
  JOB_NAME: liquibase-apply

  # Edit DB_NAME/DB_USER to your values if needed
  INSTANCE_URI: projects/autodeploydb/locations/us-central1/clusters/alloydb-cluster/instances/alloydb-primary
  DB_NAME: test_liquibase
  DB_USER: postgres

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP (JSON key)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}

      # 1) Update the Job's environment variables (includes DB password from GH Secrets)
      - name: Update Cloud Run Job env vars
        run: |
          gcloud run jobs update "${JOB_NAME}" \
            --region "${{ env.GCP_REGION }}" \
            --update-env-vars "INSTANCE_URI=${{ env.INSTANCE_URI }},DB_NAME=${{ env.DB_NAME }},DB_USER=${{ env.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD_POC }}"

      # 2) Execute the Job
      - name: Execute Cloud Run Job
        run: |
          gcloud run jobs execute "${JOB_NAME}" \
            --region "${{ env.GCP_REGION }}" \
            --wait

      # 3) (Optional but recommended for PoC) remove DB_PASSWORD from the Job config after run
      - name: Scrub DB_PASSWORD from Job config (optional)
        if: always()
        run: |
          gcloud run jobs update "${JOB_NAME}" \
            --region "${{ env.GCP_REGION }}" \
            --remove-env-vars "DB_PASSWORD"

      - name: Show Cloud Run Job logs
        run: |
          EXEC_ID=$(gcloud run jobs executions list \
            --job="${JOB_NAME}" \
            --region="${{ env.GCP_REGION }}" \
            --format="value(name)" \
            --limit=1)
          echo "Execution: $EXEC_ID"
          gcloud run jobs executions logs read "$EXEC_ID" \
            --region="${{ env.GCP_REGION }}" \
            --limit=200

