name: Liquibase - AlloyDB (self-hosted VPC runner)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, vpc]   # your runner labels
    env:
      DB_HOST: "10.3.0.2"                     # AlloyDB private IP
      DB_PORT: "5433"                         # <-- from your log
      DB_NAME: ${{ secrets.ALLOYDB_DATABASE }}
      DB_USER: ${{ secrets.ALLOYDB_DB_USER }}
      DB_PASS: ${{ secrets.ALLOYDB_DB_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Liquibase CLI
        uses: liquibase/setup-liquibase@v1
        with:
          version: "4.33.0"
          edition: "oss"

      - name: Download PostgreSQL JDBC driver
        run: |
          curl -sSL -o postgresql.jar "https://jdbc.postgresql.org/download/postgresql-42.7.4.jar"
          test -f postgresql.jar

      - name: Liquibase update (direct to private IP)
        env:
          LIQUIBASE_URL: jdbc:postgresql://${{ env.DB_HOST }}:${{ env.DB_PORT }}/${{ env.DB_NAME }}?sslmode=require
          LIQUIBASE_LOG_LEVEL: info
        run: |
          liquibase \
            --url="${LIQUIBASE_URL}" \
            --username="${DB_USER}" \
            --password="${DB_PASS}" \
            --changelog-file="changelogs/db.changelog-master.xml" \
            --classpath="${{ github.workspace }}/postgresql.jar" \
            --log-level="${LIQUIBASE_LOG_LEVEL}" \
            update

