name: Liquibase → AlloyDB via Auth Proxy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION:     ${{ secrets.ALLOYDB_REGION }}          # e.g., us-central1
      CLUSTER:    ${{ secrets.ALLOYDB_CLUSTER }}         # e.g., my-cluster
      INSTANCE:   ${{ secrets.ALLOYDB_INSTANCE }}        # e.g., primary-instance
      DB_NAME:    ${{ secrets.ALLOYDB_DATABASE }}        # e.g., appdb
      DB_USER:    ${{ secrets.ALLOYDB_DB_USER }}         # e.g., alloydbuser
      DB_PASSWORD: ${{ secrets.ALLOYDB_DB_PASSWORD }}    # optional if using IAM auth inside Postgres
      # Canonical AlloyDB instance URI
      ALLOYDB_INSTANCE_URI: projects/${{ secrets.GCP_PROJECT_ID }}/locations/${{ secrets.ALLOYDB_REGION }}/clusters/${{ secrets.ALLOYDB_CLUSTER }}/instances/${{ secrets.ALLOYDB_INSTANCE }}
      # Liquibase connects to local proxy
      LIQUIBASE_URL: jdbc:postgresql://127.0.0.1:5432/${{ secrets.ALLOYDB_DATABASE }}?sslmode=disable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 486.0.0"

      - name: Authenticate to GCP (service account JSON)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Download AlloyDB Auth Proxy
        run: |
          curl -L -o alloydb-auth-proxy https://storage.googleapis.com/alloydb-auth-proxy/v1.11.0/alloydb-auth-proxy.linux.amd64
          chmod +x alloydb-auth-proxy

      - name: Start AlloyDB Auth Proxy
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > sa.json
          ./alloydb-auth-proxy             --port=5432             --credentials-file=sa.json             "$ALLOYDB_INSTANCE_URI" &
          echo $! > proxy.pid

      - name: Wait for proxy on 5432
        shell: bash
        run: |
          for i in {1..30}; do
            (echo > /dev/tcp/127.0.0.1/5432) >/dev/null 2>&1 && exit 0
            sleep 1
          done
          echo "Proxy did not start on 5432 in time" >&2
          exit 1

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Liquibase CLI (v4.33.0 OSS)
        uses: liquibase/setup-liquibase@v1
        with:
          version: '4.33.0'
          edition: 'oss'

      - name: Download PostgreSQL JDBC driver
        run: |
          curl -L -o postgresql.jar https://jdbc.postgresql.org/download/postgresql-42.7.4.jar

      - name: Liquibase update (CLI)
        env:
          LIQUIBASE_LOG_LEVEL: info
        run: |
          liquibase             -
          -url="${LIQUIBASE_URL}"             
          --username="${DB_USER}"             
          --password="${DB_PASSWORD}"             
          --changelog-file=changelog/changelog.xml             
          --classpath=postgresql.jar             
          update

      - name: Stop proxy
        if: always()
        run: |
          if [ -f proxy.pid ]; then kill $(cat proxy.pid) || true; fi
