name: Liquibase - AlloyDB via Auth Proxy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate to GCP with a JSON key (WIF also works if you prefer)
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # (Optional) Install gcloud CLI if you need gcloud commands later
      - name: Setup gcloud CLI (optional)
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 486.0.0"

      # Download the AlloyDB Auth Proxy
      - name: Download AlloyDB Auth Proxy
        shell: bash
        run: |
          set -euo pipefail
          curl -sSL -o alloydb-auth-proxy "https://storage.googleapis.com/alloydb-auth-proxy/v1.11.0/alloydb-auth-proxy.linux.amd64"
          chmod +x alloydb-auth-proxy
          ./alloydb-auth-proxy --help >/dev/null 2>&1 || { echo "Proxy binary not runnable"; exit 1; }

      # Start the proxy on port 5432 and wait until it's listening
      - name: Start AlloyDB Auth Proxy (port 5432)
        shell: bash
        env:
          TARGET_URI: projects/${{ secrets.GCP_PROJECT_ID }}/locations/${{ secrets.ALLOYDB_REGION }}/clusters/${{ secrets.ALLOYDB_CLUSTER }}/instances/${{ secrets.ALLOYDB_INSTANCE }}
        run: |
          set -euo pipefail
          echo "Using instance URI: $TARGET_URI"
          echo '${{ secrets.GCP_SA_KEY }}' > sa.json
          chmod 600 sa.json

          ./alloydb-auth-proxy \
            --address=127.0.0.1 \
            --port=5432 \
            --credentials-file=sa.json \
            "$TARGET_URI" > proxy.log 2>&1 &

          echo $! > proxy.pid

          # Wait up to ~30s for port 5432 to open and ensure process stays alive
          for i in {1..30}; do
            if ! kill -0 "$(cat proxy.pid)" 2>/dev/null; then
              echo "Proxy process exited unexpectedly:"
              sed -n '1,200p' proxy.log || true
              exit 1
            fi
            (echo > /dev/tcp/127.0.0.1/5432) >/dev/null 2>&1 && { echo "Proxy is up"; break; }
            sleep 1
          done

          # Final check
          (echo > /dev/tcp/127.0.0.1/5432) >/dev/null 2>&1 || { echo "Port 5432 not open"; sed -n '1,200p' proxy.log || true; exit 1; }

      # Sanity: prove connectivity with psql before running Liquibase
      - name: Install psql and test connectivity
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client
          PGPASSWORD='${{ secrets.ALLOYDB_DB_PASSWORD }}' psql \
            "host=127.0.0.1 port=5432 dbname=${{ secrets.ALLOYDB_DATABASE }} user=${{ secrets.ALLOYDB_DB_USER }} sslmode=disable" \
            -c '\conninfo'

      # Install Liquibase
      - name: Setup Liquibase CLI
        uses: liquibase/setup-liquibase@v1
        with:
          version: "4.33.0"
          edition: "oss"

      # PostgreSQL JDBC driver for Liquibase
      - name: Download PostgreSQL JDBC driver
        shell: bash
        run: |
          set -euo pipefail
          curl -sSL -o postgresql.jar "https://jdbc.postgresql.org/download/postgresql-42.7.4.jar"
          test -f postgresql.jar

      # Run Liquibase update via proxy on 5432
      - name: Liquibase update
        shell: bash
        env:
          LIQUIBASE_URL: jdbc:postgresql://127.0.0.1:5432/${{ secrets.ALLOYDB_DATABASE }}?sslmode=disable
          DB_USER: ${{ secrets.ALLOYDB_DB_USER }}
          DB_PASSWORD: ${{ secrets.ALLOYDB_DB_PASSWORD }}
          LIQUIBASE_LOG_LEVEL: info
        run: |
          set -euo pipefail
          liquibase \
            --url="${LIQUIBASE_URL}" \
            --username="${DB_USER}" \
            --password="${DB_PASSWORD}" \
            --changelog-file="changelogs/db.changelog-master.xml" \
            --classpath="${{ github.workspace }}/postgresql.jar" \
            --log-level="${LIQUIBASE_LOG_LEVEL}" \
            update

      # If anything fails above, show proxy logs for quick diagnosis
      - name: Show proxy logs on failure
        if: failure()
        run: |
          echo "===== AlloyDB Auth Proxy Logs ====="
          sed -n '1,200p' proxy.log || true

      # Always stop the proxy
      - name: Stop proxy
        if: always()
        run: |
          if [ -f proxy.pid ]; then kill "$(cat proxy.pid)" || true; fi
