name: Liquibase via Cloud Run Job

on:
  push:
    branches: [main]
    paths: ['changelog/**']
  workflow_dispatch:

jobs:
  deploy-via-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker
        
      - name: Build and Deploy Cloud Run Job
        run: |
          # Build container with Liquibase and files
          cat > Dockerfile << 'EOF'
          FROM liquibase/liquibase:4.33.0
          USER root
          RUN apt-get update && apt-get install -y curl
          RUN curl -o /usr/local/bin/alloydb-auth-proxy https://storage.googleapis.com/alloydb-auth-proxy/v1.13.4/alloydb-auth-proxy.linux.amd64
          RUN chmod +x /usr/local/bin/alloydb-auth-proxy
          COPY changelog/ /liquibase/changelog/
          COPY liquibase.properties /liquibase/
          COPY run-migration.sh /usr/local/bin/
          RUN chmod +x /usr/local/bin/run-migration.sh
          ENTRYPOINT ["/usr/local/bin/run-migration.sh"]
          EOF
          
          cat > run-migration.sh << 'EOF'
          #!/bin/bash
          alloydb-auth-proxy "$ALLOYDB_INSTANCE_URI" --port=5432 --private-ip &
          PROXY_PID=$!
          sleep 15
          liquibase update
          kill $PROXY_PID
          EOF
          
          # Build and push
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/liquibase-runner .
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/liquibase-runner
          
          # Deploy as Cloud Run Job
          gcloud run jobs replace <(cat << EOF
          apiVersion: run.googleapis.com/v1
          kind: Job
          metadata:
            name: liquibase-migration
          spec:
            template:
              spec:
                template:
                  spec:
                    containers:
                    - image: gcr.io/${{ env.GCP_PROJECT_ID }}/liquibase-runner
                      env:
                      - name: ALLOYDB_INSTANCE_URI
                        value: "${{ secrets.ALLOYDB_INSTANCE_URI }}"
                      - name: LIQUIBASE_COMMAND_URL
                        value: "jdbc:postgresql://127.0.0.1:5432/${{ env.ALLOYDB_DATABASE }}"
                      - name: LIQUIBASE_COMMAND_PASSWORD
                        value: "${{ env.ALLOYDB_PASSWORD }}"
                    serviceAccountName: liquibase-alloydb-sa@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com
                    vpcAccess:
                      connector: projects/${{ env.GCP_PROJECT_ID }}/locations/us-central1/connectors/your-vpc-connector
          EOF
          )
          
          # Execute the job
          gcloud run jobs execute liquibase-migration --region=us-central1 --wait