name: Liquibase → AlloyDB via Auth Proxy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION:     ${{ secrets.ALLOYDB_REGION }}          # e.g., us-central1
      CLUSTER:    ${{ secrets.ALLOYDB_CLUSTER }}         # e.g., my-cluster
      INSTANCE:   ${{ secrets.ALLOYDB_INSTANCE }}        # e.g., primary-instance
      DB_NAME:    ${{ secrets.ALLOYDB_DATABASE }}        # e.g., appdb
      DB_USER:    ${{ secrets.ALLOYDB_DB_USER }}         # e.g., alloydbuser
      DB_PASSWORD: ${{ secrets.ALLOYDB_DB_PASSWORD }}    # optional if using IAM auth inside Postgres
      # Canonical AlloyDB instance URI
      ALLOYDB_INSTANCE_URI: projects/${{ secrets.GCP_PROJECT_ID }}/locations/${{ secrets.ALLOYDB_REGION }}/clusters/${{ secrets.ALLOYDB_CLUSTER }}/instances/${{ secrets.ALLOYDB_INSTANCE }}
      # Liquibase connects to local proxy
      LIQUIBASE_URL: jdbc:postgresql://127.0.0.1:5432/${{ secrets.ALLOYDB_DATABASE }}?sslmode=disable

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 486.0.0"

      - name: Authenticate to GCP (service account JSON)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Download AlloyDB Auth Proxy
        run: |
          curl -sSL -o alloydb-auth-proxy "https://storage.googleapis.com/alloydb-auth-proxy/v1.11.0/alloydb-auth-proxy.linux.amd64"
          chmod +x alloydb-auth-proxy
          ./alloydb-auth-proxy --version

      - name: Start AlloyDB Auth Proxy (verbose, port 6543)
        env:
          TARGET_URI: projects/${{ secrets.GCP_PROJECT_ID }}/locations/${{ secrets.ALLOYDB_REGION }}/clusters/${{ secrets.ALLOYDB_CLUSTER }}/instances/${{ secrets.ALLOYDB_INSTANCE }}
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > sa.json
          # Run proxy with verbose logging and bind explicitly to loopback on port 6543
          ./alloydb-auth-proxy \
            --verbose \
            --address=127.0.0.1 \
            --port=6543 \
            --credentials-file=sa.json \
            "$TARGET_URI" > proxy.log 2>&1 &
          echo $! > proxy.pid
          # Wait for the port to open
          for i in {1..30}; do (echo > /dev/tcp/127.0.0.1/6543) >/dev/null 2>&1 && echo "Proxy up" && break; sleep 1; done
          # Show the last few lines now; we will also cat this file if anything fails later
          tail -n 50 proxy.log || true

      - name: Install psql client and test connectivity
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client
          # Try a lightweight connection first (no query)
          PGPASSWORD='${{ secrets.ALLOYDB_DB_PASSWORD }}' psql \
            "host=127.0.0.1 port=6543 dbname=${{ secrets.ALLOYDB_DATABASE }} user=${{ secrets.ALLOYDB_DB_USER }} sslmode=disable" \
            -c '\conninfo'

      - name: Setup Liquibase CLI (v4.33.0 OSS)
        uses: liquibase/setup-liquibase@v1
        with:
          version: "4.33.0"
          edition: "oss"

      - name: Download PostgreSQL JDBC driver
        run: curl -sSL -o postgresql.jar "https://jdbc.postgresql.org/download/postgresql-42.7.4.jar"

      - name: Liquibase update (use proxy on 6543)
        shell: bash
        env:
          LIQUIBASE_URL: jdbc:postgresql://127.0.0.1:6543/${{ secrets.ALLOYDB_DATABASE }}?sslmode=disable
          DB_USER: ${{ secrets.ALLOYDB_DB_USER }}
          DB_PASSWORD: ${{ secrets.ALLOYDB_DB_PASSWORD }}
          LIQUIBASE_LOG_LEVEL: info
        run: |
          set -euo pipefail
          liquibase \
            --url="${LIQUIBASE_URL}" \
            --username="${DB_USER}" \
            --password="${DB_PASSWORD}" \
            --changelog-file="changelogs/db.changelog-master.xml" \
            --classpath="${{ github.workspace }}/postgresql.jar" \
            --log-level="${LIQUIBASE_LOG_LEVEL}" \
            update

      - name: If failure, show proxy logs
        if: failure()
        run: |
          echo "===== AlloyDB Auth Proxy Logs ====="
          tail -n +1 proxy.log || true

      - name: Stop proxy
        if: always()
        run: |
          if [ -f proxy.pid ]; then kill "$(cat proxy.pid)" || true; fi


          
      - name: Stop proxy
        if: always()
        run: |
          if [ -f proxy.pid ]; then kill $(cat proxy.pid) || true; fi
